name: superstr_test
channels:
  - defaults
  - conda-forge
dependencies:
  - python =3.8.3
  - numpy =1.20.1
  - matplotlib =3.4.1
  - pandas =1.2.2
  - bashtage::arch =4.15
  - mpmath =1.2.1
  - scipy =1.6.1
  - statsmodels =0.12.2
  - tqdm =4.59
  - seaborn =0.11.1
  - requests =2.28.0
  - pyfaidx =0.7.0
  - scikit-learn =